/*
Copyright (c) 2021 - 2026 Chief Mechanic Limited
Confidential and Proprietary - All rights reserved.
*/
var cm_socket;var cm_socket_data={'o':!1,'oi':!1,'w':!1,'b':!1,'r':0,'t':0,'tf':!1,'u':{},'ob':!1,'of':!1,'ur':0,'m':!1,'v':0,'pt':document.title};var cm_socket_host='wss://core.motordesk.com/_ws_/';var cm_page_title=document.title;var cm_socket_player={};var cm_chat_text_welcome='How can we help?';var cm_chat_text_offline='We\'re currently offline but we will reply as soon as possible! How would you like us to contact you?';$(document).ready(function(){$('#cm_chat_icon').show();cm_chat_volume();cm_chat_init();$('#cm_chat_send').on('click',function(){cm_chat_send();$('#cm_chat_message').focus()});$('#cm_chat .exit').on('click',function(){cm_chat_close()});$('#cm_chat_message').on('keyup',function(e){var code=e.keyCode?e.keyCode:e.which;if(code==13){cm_chat_send()}else{var time=Math.floor(Date.now()/1000);if(cm_socket_data.t<time){cm_socket_data.t=time+5;cm_chat_type()}}});$('#cm_chat_start').on('click',function(){cm_chat_start();$('#cm_chat_message').focus()});$('#cm_chat_volume').on('click',function(){if(cm_socket_data.m==!0){cm_cookie_save('CM-CHAT-VOLUME','false')}else{cm_cookie_save('CM-CHAT-VOLUME','true')}
cm_chat_volume()})});function cm_socket_init(reconnect){cm_socket_data.oi=!0;if(typeof cm_data=='undefined'){return!1}
try{cm_socket=new WebSocket(cm_socket_host);cm_socket.onopen=function(data){cm_socket_data.o=!0;cm_data.w=window.location.href;cm_socket_send({'t':'auth','d':cm_data});cm_chat_begin()};cm_socket.onmessage=function(data){cm_socket_receive(data)};cm_socket.onclose=function(data){cm_socket_data.o=!1;cm_socket_reconnect()}}catch(exception){cm_chat_status('connect')}}
function cm_socket_send(data){if(cm_socket_data.oi===!1){cm_socket_init()}
try{cm_socket.send(JSON.stringify(data));cm_chat_status('');return!0}catch(exception){setTimeout(function(){cm_chat_status('message')},'100');return!1}}
function cm_socket_close(){if(cm_socket!=null){cm_socket.close();cm_socket=null}}
function cm_socket_reconnect(){if(cm_socket_data.w===!1){cm_chat_status('Connecting...')}else{cm_chat_status('Reconnecting...')}
cm_socket_close();cm_socket_data.r++;setTimeout(function(){if(cm_socket_data.o===!1){cm_socket_init()}},parseInt(cm_socket_data.r)*1000)}
function cm_socket_receive(data){data=JSON.parse(data.data);if(typeof data.t!='undefined'){if(data.t=='msg'){if(cm_socket_data.of!==!1){clearTimeout(cm_socket_data.of);cm_socket_data.of=!1;cm_chat_status('')}
$('#cm_chat .message .offline').remove();cm_chat_receive(data,!0);if(cm_socket_data.tf!==!1){cm_chat_status('');clearTimeout(cm_socket_data.tf);cm_socket_data.tf=!1}
if(cm_cookie('CM-CHAT')!='true'){cm_socket_data.ur++;cm_chat_unread(!0)}else{cm_chat_viewed(data.d.i,!0)}
cm_chat_audio('received');cm_chat_title('received');if(typeof data.d.o=='undefined'){cm_cookie_save('CM-CHAT-OFFLINE','')}}else if(data.t=='mirror_msg'){var time_now=Math.floor(Date.now()/1000);cm_chat_message(time_now,'sent',data.d.f,data.d,time_now);cm_chat_scroll()}else if(data.t=='type'){if(cm_socket_data.of!==!1){clearTimeout(cm_socket_data.of);cm_socket_data.of=!1;cm_chat_status('')}
if(cm_socket_data.tf!==!1){clearTimeout(cm_socket_data.tf)}
$('#cm_chat .message .offline').remove();cm_chat_status('Operator is typing...');cm_socket_data.tf=setTimeout(function(){cm_chat_status('');cm_socket_data.tf=!1},7000)}else if(data.t=='acknowledge'){if(cm_socket_data.of!==!1){clearTimeout(cm_socket_data.of);cm_socket_data.of=!1;cm_chat_status('')}
if(cm_socket_data.tf!==!1){clearTimeout(cm_socket_data.tf)}
cm_chat_status('')}else if(data.t=='begin'){if(cm_socket_data.b!==!1){for(var i=0;i<data.m.length;i++){if(data.m[i].sender!=0){if($('#cm_chat_message_'+data.m[i].id).length==0){i=data.m.length;$('#cm_chat .message > div').html('');cm_socket_data.b=!1;cm_socket_data.ur=0}}}}
if(cm_socket_data.b===!1){cm_socket_data.u=data.u;if(data.m.length>0){cm_socket_data.b=data.m.length;for(var i=0;i<data.m.length;i++){if(data.m[i].sender==0){cm_chat_message(data.m[i].id,'sent',data.m[i].sender,data.m[i].message,data.m[i].created)}else{cm_chat_message(data.m[i].id,'received',data.m[i].sender,data.m[i].message,data.m[i].created);if(data.m[i].viewed=='0'){if(cm_cookie('CM-CHAT')=='true'){cm_chat_viewed(data.m[i].id,!0)}else{cm_chat_viewed(data.m[i].id,!1);cm_socket_data.ur++}}}}
$('#cm_chat .start').hide();$('#cm_chat .chat').show();cm_cookie_save('CM-CHAT-SESSION','true');cm_chat_scroll();var offline=cm_cookie('CM-CHAT-OFFLINE');if((offline!==!1)&&(offline!=='')){offline=offline.split(':');if(offline[0]==0){if(offline[1]<(Date.now()-70000)){cm_chat_offline(!0,!1,!1)}else{cm_chat_offline(!1,(Date.now()-offline[1]),!0)}}else if(offline[0]==1){cm_chat_offline(!0,!1,!1)}}}
cm_chat_unread(!1)}}else if(data.t=='offline'){cm_chat_offline(!1,!1,!0)}else if(data.t=='error'){if(typeof data.d.i!='undefined'){if($('#cm_chat_message_'+data.d.i).length>0){$('#cm_chat_message_'+data.d.i).remove()}}
$('#cm_chat_message').val(data.d.m);setTimeout(function(){cm_chat_status('message')},'100')}}}
function cm_chat_init(){$('#cm_chat_icon').on('click',function(){cm_chat_open();$('#cm_chat_message_start').focus()});if((cm_cookie('CM-CHAT-SESSION')=='true')||(cm_cookie('CM-CHAT')=='true')){if(cm_socket_data.o===!1){cm_socket_init()}}
if(cm_cookie('CM-CHAT')=='true'){cm_chat_open()}}
function cm_chat_open(){if(cm_socket_data.oi===!1){cm_socket_init()}
cm_cookie_save('CM-CHAT','true');if(cm_cookie('CM-CHAT-SESSION')=='true'){$('#cm_chat .start').hide();$('#cm_chat .chat').show();if(cm_socket_data.ur>0){cm_chat_viewed(!1,!0);cm_socket_data.ur=0;cm_chat_unread(!1)}
cm_chat_scroll()}else{$('#cm_chat .chat').hide();$('#cm_chat .start').show()}
$('#cm_chat').show();$('#cm_chat_icon').hide();if(cm_cookie('CM-CHAT-SESSION')=='true'){$('#cm_chat_message').focus()}}
function cm_chat_close(){cm_cookie_save('CM-CHAT','false');$('#cm_chat_icon').show();$('#cm_chat').hide()}
function cm_chat_begin(){if(cm_socket_data.w===!1){cm_socket_data.w=!0;var data={'t':'msg','d':{'f':'site','m':cm_chat_text_welcome}};cm_chat_receive(data,!1)}
$('#cm_chat .loading').hide();cm_chat_status('')}
function cm_chat_send(){var message=$('#cm_chat_message').val();message=message.trim();var time_now=Math.floor(Date.now()/1000);if(message!=''){var data={'t':'msg','d':{'i':time_now,'f':'0','m':message}};if(cm_socket_send(data)===!0){cm_chat_message(time_now,'sent',data.d.f,data.d,time_now);cm_chat_scroll();$('#cm_chat_message').val('');cm_cookie_save('CM-CHAT-SESSION','true')}}else{$('#cm_chat_message').val('')}}
function cm_chat_type(){try{cm_socket.send(JSON.stringify({'t':'type'}))}catch(exception){}}
function cm_chat_receive(data,scroll){if(typeof data.t!='undefined'){if((data.t=='msg')&&(typeof data.d.f!='undefined')){cm_chat_message(data.i,'received',data.d.f,data.d,!1);if(scroll===!0){cm_chat_scroll()}}}}
function cm_chat_message(id,type,sender,message,created){if(message!=''){if(created===!1){created=Math.floor(Date.now()/1000)}
if(sender=='0'){from=''}else if((sender=='site')||(sender=='-1')){from=''}else{if(typeof cm_socket_data.u[sender]!='undefined'){if(cm_socket_data.u[sender].i===!0){from='<img src="/media/user/'+sender+'/profile.png" class="avatar" />'}else{if(cm_socket_data.u[sender].n!=''){var name=cm_socket_data.u[sender].n;initials=cm_safe(name);initials=initials.trim().split(' ');var initials_count=parseInt(initials.length)-1;from=initials[0][0];if(initials[initials_count]==''){initials_count--}
if(initials_count>0){from+=initials[initials_count][0]}
from='<span class="avatar initials">'+from+'</span>'}}}
if(from==''){from=''}}
var output='<div';if(id!==!1){output+=' id="cm_chat_message_'+id+'"'}
output+='>'+from+'<div class="rounded '+cm_safe(type)+'">';if(typeof message.mt!='undefined'){var url=message.mf;if(url.substr(0,8)!='https://'){url='/media/message/'+url}
if(message.mt=='i'){output+='<a href="'+url+'" target="blank"><img src="'+url+'" class="cm_lead_message_media" alt="" /></a>'}else if(message.mt=='vi'){output+='<video id="cm_message_'+id+'_video" crossorigin playsinline controls class="cm_lead_message_media"><source src="'+url+'" /></video>';cm_socket_player[id]=new Plyr('#cm_message_'+id+'_video',{})}
if(typeof message.m!='undefined'){output+='<br />'}}
if(typeof message.m!='undefined'){output+=cm_text_link(cm_safe(message.m).replace(/(\n)+/g,'<br />'))}
output+='</div></div>';$('#cm_chat .message > div').append(output);$('#cm_chat .message').show()}}
function cm_chat_start(){$('#cm_chat_message_start').removeClass('is-invalid');var name='';var email='';var phone='';var message=$('#cm_chat_message_start').val();if(message!=''){message=message.trim()}
if(cm_socket_data.o===!1){$('#cm_chat_start').html('Unable to Connect')}
if(message!=''){var data={'t':'start','d':{'f':'0','n':name,'e':email,'p':phone,'m':message}};if(cm_socket_send(data)===!0){$('#cm_chat .start').hide();$('#cm_chat .chat').show();cm_chat_message(!1,'sent',data.d.f,data.d,!1);cm_chat_scroll();$('#cm_chat_message').val('');cm_cookie_save('CM-CHAT-SESSION','true');cm_socket_data.of=setTimeout(function(){cm_chat_offline(!1,!1,!0)},60000)}}else{$('#cm_chat_message_start').addClass('is-invalid')}}
function cm_chat_offline(confirm,cookie,audio){if(confirm===!1){var offline=cm_cookie('CM-CHAT-OFFLINE');var offline_skip=!1;if((offline!==!1)&&(offline!=='')){offline=offline.split(':');if((offline[0]==2)&&(offline[1]>(Date.now()-3600000))){offline_skip=!0}}
if(offline_skip===!1){if(cookie===!1){cm_cookie_save('CM-CHAT-OFFLINE','0:'+Date.now());cm_socket_data.ob=setTimeout(function(){cm_chat_status('Waiting for operator...')},1500)}else{cm_chat_status('Waiting for operator...')}
var delay=60000;if(cookie!==!1){delay=delay-cookie;if(delay<1000){delay=1000}}
cm_socket_data.of=setTimeout(function(){cm_chat_offline(!0,!1,!0);cm_cookie_save('CM-CHAT-OFFLINE','1:'+Date.now())},delay)}}else{cm_chat_status('');$('#cm_chat .message .offline').remove();var output='<div class="offline mb-2"><div><small>'+cm_chat_text_offline+'</small></div><div class="chat-channel pt-1">';output+='<button id="cm_chat_sms_button" class="btn btn-sm btn-icon btn-outline active w-100"><i class="bi bi-chat-dots"></i>Text Message</button><div id="cm_chat_sms_div" style="display:none;" class="mt-3 mb-4"><label for="cm_chat_sms">What\'s your mobile number?</label><div class="input-group mt-2"><input type="number" id="cm_chat_sms" placeholder="07000 123123" step="1" class="form-control" /><button id="cm_chat_sms_save" class="btn btn-outline">Save</button></div></div>';output+='<button id="cm_chat_phone_button" class="btn btn-sm btn-icon btn-outline w-100"><i class="bi bi-telephone"></i>Telephone</button><div id="cm_chat_phone_div" style="display:none;" class="mt-3 mb-4"><label for="cm_chat_phone">What\'s your telephone number?</label><div class="input-group mt-2"><input type="number" id="cm_chat_phone" placeholder="01234 123123" step="1" class="form-control" /><button id="cm_chat_phone_save" class="btn btn-outline">Save</button></div></div>';output+='<button id="cm_chat_email_button" class="btn btn-sm btn-icon btn-outline w-100"><i class="bi bi-envelope"></i>Email</button><div id="cm_chat_email_div" style="display:none;" class="mt-3 mb-4"><label for="cm_chat_email">What\'s your email address?</label><div class="input-group mt-2"><input type="email" id="cm_chat_email" placeholder="you@email.com" class="form-control" /><button id="cm_chat_email_save" class="btn btn-outline">Save</button></div></div></div></div>';$('#cm_chat .message > div').append(output);$('#cm_chat_sms_button').on('click',function(){$('#cm_chat_phone_div').hide();$('#cm_chat_email_div').hide();$('#cm_chat_sms_div').show()});$('#cm_chat_sms_save').on('click',function(){cm_chat_offline_save('sms')});$('#cm_chat_phone_button').on('click',function(){$('#cm_chat_sms_div').hide();$('#cm_chat_email_div').hide();$('#cm_chat_phone_div').show()});$('#cm_chat_phone_save').on('click',function(){cm_chat_offline_save('phone')});$('#cm_chat_email_button').on('click',function(){$('#cm_chat_sms_div').hide();$('#cm_chat_phone_div').hide();$('#cm_chat_email_div').show()});$('#cm_chat_email_save').on('click',function(){cm_chat_offline_save('email')});cm_chat_scroll();if(audio===!0){cm_chat_audio('received');cm_chat_title('received')}}}
function cm_chat_offline_save(type){$('#cm_chat_sms').removeClass('is-invalid');$('#cm_chat_phone').removeClass('is-invalid');$('#cm_chat_email').removeClass('is-invalid');$('#cm_chat_'+type+'_save').html('Save');var valid=!0;if($('#cm_chat_'+type).val()==''){valid=!1}else if(type=='email'){var reg=/\S+@\S+\.\S+/;valid=reg.test($('#cm_chat_'+type).val())}
if(valid===!1){$('#cm_chat_'+type).addClass('is-invalid')}else{$('#cm_chat_'+type+'_save').html('<span class="spinner-border spinner-border-sm me-1" role="status"></span>Saving');var data={'t':'offline_save','d':{'t':type,'v':$('#cm_chat_'+type).val()}};if(cm_socket_send(data)===!0){$('#cm_chat_'+type+'_save').html('<i class="bi bi-check me-1"></i>Saved');cm_cookie_save('CM-CHAT-OFFLINE','2:'+Date.now())}else{$('#cm_chat_'+type+'_save').html('<i class="bi bi-x me-1"></i>Save Failed')}}}
function cm_chat_scroll(){var height=$('#cm_chat .message > div').height();$("#cm_chat .message").animate({scrollTop:height},100);setTimeout(function(){if($('#cm_chat .message > div').height()>height){cm_chat_scroll()}},100)}
function cm_chat_status(status){if(cm_socket_data.ob!==!1){clearTimeout(cm_socket_data.ob);cm_socket_data.ob=!1}
if(status=='connect'){$('#cm_chat .status').html('<i class="bi bi-exclamation-triangle pm2"></i> Unable to connect.').show()}else if(status=='message'){$('#cm_chat .status').html('<i class="bi bi-exclamation-triangle pm2"></i> Unable to send message, please try again.').show()}else{$('#cm_chat .status').html(status).show()}}
function cm_chat_viewed(view_id,send){if((view_id!==!1)&&(view_id>cm_socket_data.v)){cm_socket_data.v=view_id}
if(send===!0){try{cm_socket.send(JSON.stringify({'t':'view','d':{'i':cm_socket_data.v}}))}catch(exception){}}}
function cm_chat_unread(notify){if(cm_socket_data.ur>0){if($('#cm_chat_icon > span').length>0){$('#cm_chat_icon > span').html(cm_socket_data.ur)}else{$('#cm_chat_icon').append('<span class="pulse">'+cm_socket_data.ur+'</span>')}}else{$('#cm_chat_icon > span').remove()}}
function cm_chat_audio(type){if(cm_socket_data.m===!0){return!1}
var audio=$('#cm_chat_audio_'+type)[0];audio.volume=0.5;audio.play();return!0}
function cm_chat_title(type){if(type=='received'){document.title='New Message Received!';setTimeout(function(){document.title=cm_socket_data.pt},'2000')}}
function cm_chat_volume(){if(cm_cookie('CM-CHAT-VOLUME')=='true'){cm_socket_data.m=!0}else{cm_socket_data.m=!1}
if(cm_socket_data.m==!0){$('#cm_chat_volume').addClass('bi-volume-mute-fill').removeClass('bi-volume-up-fill')}else{$('#cm_chat_volume').addClass('bi-volume-up-fill').removeClass('bi-volume-mute-fill')}}